---
driver:
  name: vagrant

provisioner:
  name: policyfile_zero

platforms:
  - name: ubuntu-12.04
  - name: centos-6.5
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[test_stunnel::default]
  - name: certificates
    run_list:
      - recipe[test_stunnel::certificates]
