name             "stunnel"
maintainer       "dylancanfield"
maintainer_email "dylan.canfield@colorado.edu"
license          "Apache 2.0"
description      "Installs/Configures stunnel"
version          "2.2.0"
